# Generated by Django 4.2.16 on 2024-09-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название машины')),
                ('description', models.TextField(verbose_name='Название описание')),
                ('image', models.ImageField(upload_to='')),
                ('car_type', models.CharField(choices=[('Седан', 'Седан'), ('Пикап', 'Пикап'), ('Купе', 'Купе'), ('Унивесал', 'Универса'), ('Минивен', 'Минивен')], max_length=100)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('video', models.URLField()),
            ],
        ),
    ]
